// Generated by joist-codegen (hash=b63cee)
import { Resolvers } from 'src/generated/graphql-types';


    type EnumDetails = never;

    export const enumResolvers: Pick<Resolvers, EnumDetails> = {

    };
